### ISSUE TITLE
Umbrella issue

### ISSUE THREAD

**Issue by rtsao** [rtsao/ess#1]
- [ ] Language design
    - [ ] Modules
    - [x] Comments
    - [x] Element definitions
    - [ ] Element composition
    - [ ] Transformation syntax
    - [x] Pattern matching
    - [ ] Variable declaration
    - [ ] CSS escape hatches
- [ ] Compiler
   - [ ] Front end
       - [x] Lexer
       - [x] Parser
       - [ ] Quality error messages
   - [ ] Middle end
       - [x] AST traversal and IR generator
       - [x] Declaration atomizer
       - [ ] Type checker
       - [ ] Algebraic expression simplifier
       - [x] Pattern matching optimizer
       - [ ] RTL generator
   - [x] Backend
      - [x] JS/CSS codegen
      - [x] Flow type annotations
- [ ] LSP
   - [ ] Syntax highlighting
   - [ ] Autocomplete
- [ ] Webpack loader/plugin
  - [ ] Basic
  - [ ] Good
- [ ] Pretty printer/formatter (refmt/prettier)
- [ ] Chrome DevTools extension (like https://github.com/rtsao/styletron/pull/111)
